### PR TITLE
Add SDL 1.2 dev libs

### PR DESCRIPTION
**Pull request by apiraino**
These are not strictly required but a nice to have when building AROS.

Would it make sense to add this to the general base image?

### CODE REVIEW

**Comment by MBeijer** [comment]
It makes sense when building AROS in general, and since we're building AROS in our Jenkins server with this base image, I say why not. But perhaps we should have two base images. One for building AROS + the other toolchains, and one base for all docker images. We don't really need regular gcc in the environment where the crosstools are. 

I'd like to keep the environments slim so they're quick to download and get started with. What do you say? :)

**Comment by apiraino** [comment]
I agree, let's keep base images as lean and slim as possible.

When I've figured out the complete Docker roundtrip for AROS, we can optimize here and there (f.e.  I'd like to test Alpine for Docker base images).

**Comment by MBeijer** [comment]
Yeah, I've been thinking about that as well. Ubuntu to build the
crosstools, copy crosstools and set environment in alpine. People running
build-servers will be happier as well. :D

**Comment by apiraino** [comment]
I've thought a bit about this. I'm not sure how can we "export" or "copy" a compiled crosstoolchain into another docker recipe file without breaking it.

if we want to slim down the images size we can start with:
- testing another base image (like Alpine or else) in this repo
- remove the whole `gcc` toolchains and all unneeded stuff from [the final images](https://github.com/AmigaPorts/docker-amiga-gcc) once the building image is done.

Thoughts on this?

**Comment by MBeijer** [comment]
The current toolchains copy everything that is needed and work totally
fine. So I don’t understand what you mean?

**Pull request merged**
